Allow different combinations of mocked prereqs

diff --git a/test/bin/bosh b/test/bin/bosh
--- a/test/bin/bosh
+++ b/test/bin/bosh
@@ -1,3 +1,6 @@
 #!/usr/bin/env bash
 
-echo $*
+if [ "$1" != "target" ] && ([ "$1" != "sync" ] || [ "$2" != "blobs" ]); then
+  >&2 echo "Error: Expect nothing but '$BASH_SOURCE sync blobs' or '$BASH_SOURCE target'"
+  exit 1
+fi
